### ISSUE TITLE
Missing file for example script

### ISSUE THREAD

**Issue by amnamasood-amd** [HPMLL/BurstGPT#1]
Hi, 

I am trying to run the example script (server.sh) and there is a missing file:

{'seed': 0, 'surplus_prompts_num': 16384, 'use_burstgpt': False, 'burstgpt_path': '/hpc2hdd/home/ychen906/repo/BurstGPT/data/BurstGPT_without_fails.csv', 'conv_or_api': 'conv', 'scale': 100, 'prompt_num': 500}
None
prefill record
prefill generate idx in one prompt len
prefill prompt len
prefill prompt len via prompt
Traceback (most recent call last):
  File "/workspace/BurstGPT/example/ForwardEnd2end/scripts/vllm_profile/profile_vllm_server.py", line 90, in <module>
    server = ServerOnline(model_path=args.model_path,
  File "/workspace/BurstGPT/example/ForwardEnd2end/scripts/vllm_profile/../../profile_server/server.py", line 312, in __init__
    self.queries = self._Query(qps=self.qps, inputs=self.inputs, trace=self.trace, conv_or_api=self.conv_or_api)
  File "/workspace/BurstGPT/example/ForwardEnd2end/scripts/vllm_profile/../../profile_server/server.py", line 106, in __init__
    df = pd.read_csv('/data/work_days_avg_gamma_per20min_conv_filtered_8_to_plus_1.csv')
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/work_days_avg_gamma_per20min_conv_filtered_8_to_plus_1.csv'

**Comment by amnamasood-amd** [comment]
Thank you. Can you also tell me where to download shareGPT_prompt.json file from?

**Comment by lzzmm** [comment]
Hi, sorry for the confusion caused, this file contains prompt data from share_GPT like [ShareGPT_Vicuna_unfiltered](https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/tree/main/HTML_cleaned_raw_dataset). You can choose your prompt pool and process it into format like [example/ForwardEnd2end/preprocess_data/shareGPT.json](https://github.com/HPMLL/BurstGPT/blob/main/example/ForwardEnd2end/preprocess_data/shareGPT.json), [example/ForwardEnd2end/preprocess_data/pre_shareGPT.py](https://github.com/HPMLL/BurstGPT/blob/main/example/ForwardEnd2end/preprocess_data/pre_shareGPT.py) provides a example to preprocess data.

**Comment by lzzmm** [comment]
You can also use [example/ForwardEnd2end/preprocess_data/shareGPT.json](https://github.com/HPMLL/BurstGPT/blob/main/example/ForwardEnd2end/preprocess_data/shareGPT.json) for simply running an example.
